Localisation_App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views


'''
BELOW URL PATTERNS CONTAINS THE VARIOUS URLS AND THEIR RESPECTIVE CALLING VIEWS .
THE REQUEST KEYWORDS IN URL ARE MAPPED IN THIS URLPATTERN BLOCK TO DIFFERENT VIEWS WITH NAME
SITEMAP OF WEBSITE CAN BE MADE USING ALL THE URLS MENTIONED HERE IN URLPATTERN BLOCK .
'''


app_name = 'Localisation_App'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('toolsPage/', views.toolsPage, name='toolsPage'),
    path('toolsPage/<id>', views.toolsPage, name='toolsPage'),
    path('tools/', views.tools, name='tools'),
    path('toolsDownloadCounter/<int:id>',
         views.toolsDownloadCounter, name='toolsDownloadCounter'),
    path('toolsReset/', views.toolsReset, name='toolsReset'),
    path('toolsSearch/', views.toolsSearch, name='toolsSearch'),
    path('resourcesPage/', views.resourcesPage, name='resourcesPage'),
    path('resourcesPage/<id>', views.resourcesPage, name='resourcesPage'),
    path('resources/', views.resources, name='resources'),
    path('resourceDownloadCounter/<int:id>',
         views.resourceDownloadCounter, name='resourceDownloadCounter'),
    path('resourcesReset/', views.resourcesReset, name='resourcesReset'),
    path('resourceSearch/',
         views.resourceSearch, name='resourceSearch'),
    path('services/', views.services, name='services'),
    path('successstoryPage/', views.successstoryPage, name='successstoryPage'),
    path('successstory/', views.successstory, name='successstory'),
    path('successstorySearch/',
         views.successstorySearch, name='successstorySearch'),
    path('successstoryPage/<id>',views.successstoryPage, name='successstoryPage'),
    #     path('successstoryReset/', views.successstoryReset, name='successstoryReset'),
    path('submit/', views.submit, name='submit'),
    path('faqs/', views.faqs, name='faqs'),
    path('faqs/<data>',views.faqs,name='faqs'),
    path('faqsSearch/', views.faqsSearch, name='faqsSearch'),
    path('contactus/', views.contactus, name='contactus'),
    path('websitepolicy/', views.websitepolicy, name='websitepolicies'),
    path('websitepolicy/<int:id>', views.websitepolicydata,
         name='websitepolicydata'),
    path('termsandcondition/', views.termsandcondition, name='termsandcondition'),
    path('accessibilityStatement/', views.accessibilityStatement,
         name='accessibilityStatement'),
    path('sitemap/', views.sitemap, name='sitemap'),
    path('help/', views.help, name='help'),
    path('submit/<img>', views.submit, name='submit'),
    path('help/<int:id>', views.helpData, name='helpData'),
    path('srvEnableTyping/', views.srvEnableTyping, name='srvEnableTyping'),
    path('srvGoTranslateWebLocalizer/', views.srvGoTranslateWebLocalizer,
         name='srvGoTranslateWebLocalizer'),
    path('srvOnscreenKeyboard/', views.srvOnscreenKeyboard,
         name='srvOnscreenKeyboard'),
    path('srvTTS/', views.srvTTS, name='srvTTS'),
    path('srvTransliteration/', views.srvTransliteration,
         name='srvTransliteration'),


    path('goTranslate/', views.goTranslate,
         name='goTranslate'),
#     path('translation-quote/', views.translation_quote,
#          name='translation_quote'),
#     path('translation-quote-user-dashboard', views.translation_quote_user_dashboard,
#          name='translation_quote_user_dashboard'),
#     path('translation-quote-show/<str:application_number>/',
#          views.translation_quote_show, name='translation_quote_show'),
    #     path('dashboard2', views.dashboard2, name="dashboard2"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('machine-translation/', views.machine_translation,
         name="machine_translation"),
    path('name-matcher/', views.name_matcher, name="name_matcher"),
    path('empanelled_agencies/', views.empanelled_agencies,
         name="empanelled_agencies"),
    path('bhashini/', views.bhashini, name="bhashini"),
    path('anuvaad/', views.anuvaad, name="anuvaad")

]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

Localisation_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('', include('Localisation_App.urls')),
    path('search/', include('search.urls')),
]

handler404 = 'Localisation_App.views.custom_page_not_found_view'
handler500 = 'Localisation_App.views.custom_error_view'
handler403 = 'Localisation_App.views.custom_permission_denied_view'
handler400 = 'Localisation_App.views.custom_bad_request_view'

search/urls.py
from django.urls import path
from . import views


app_name= 'search'
urlpatterns = [
    path('', views.search , name='search'),

]

Localisation_App/views.py
from django.forms import ValidationError
from Localisation_Project.settings import CACHE_TTL
from .forms import TTSservice, TranslationQuoteForm
from django.contrib import messages
from django.core.mail import send_mail
from django.core.paginator import Paginator
from multiprocessing import context
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from .models import *
import random
import requests
from .word_count import crawl_data
from django.contrib.auth.models import User
import uuid
from datetime import date, datetime
from .helpers import *
import json
from bson import json_util
from django.urls import resolve
from django.contrib.auth.decorators import login_required
import logging
from datetime import date
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.core.cache import cache
from django.core import validators
logger = logging.getLogger('django')
# global str_num
# global url
CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)
import base64
import logging
import traceback
from django.conf import settings
from django.views.decorators.cache import cache_control
from dateutil import parser
from django.shortcuts import render

# Home Page View Starts

''' 
AUTHOR : SHWETA PATIL
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON HOME PAGE WITH TOP AND FOOTER MENUS.

'''


def home(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        articleData = fetch_all_article_data()
        services_name_data_list = fetch_services_heading_data()
        newsAndEventsData = fetch_all_newsAndEvents_data()
        logger.info("Finally, Home page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
            'NewsAndEventsData': newsAndEventsData,
            'Servicesdata': services_name_data_list
        }
        return render(request, 'Localisation_App/home.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Exception : Error in Home page. redirecting to error page ")
        
# Home Page View Ends

# About Us Page View Starts


''' 
AUTHOR : SHWETA PATIL
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON ABOUT US PAGE WITH TOP AND FOOTER MENUS.
THIS DYNAMIC CONTENT OF ABOUT US PAGE IS BEING RENDERED FROM 'Article' MODEL.
FOR CHANGING THE CONTENT OF ABOUT US PAGE, CHANGE THE CONTENT IN 'Article' MODEL FROM BACHEND ADMIN.
'''


def aboutus(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        logger.info("About Us URL fetched and set in 'requested_url' session")
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        articleData = fetch_aboutus_data()
        logger.info("Finally, About Us page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
        }
        return render(request, 'Localisation_App/aboutus.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Exception : Error in About Us page. redirecting to error page ")
        # 
    

# About Us Page View Ends

# Faqs Page Views Starts


''' 
AUTHOR : SHWETA PATIL
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON FAQS PAGE WITH TOP AND FOOTER MENUS.

'''


def faqs(request, data=None):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        if data==None:
            faqs_data = fetch_faqs_data()
            logger.info("Finally, Faqs page getting displayed")
            # print("faqsdata",faqs_data)
            for d in faqs_data:
                print("q",d.FAQs_Question)
                print("a",d.FAQs_Answer)
            context = {
                'data': faqs_data,
                'FooterMenuItemsdata': footer_menu_items_data,
                'topmenus': top_menu_items_data,
                'faq_title': 'none'
            }
        
        else:
            chosen_faqs = FAQs.objects.filter(id=data)
            context={
            'data':chosen_faqs,
            'FooterMenuItemsdata':footer_menu_items_data,
            'topmenus':top_menu_items_data,
            'faq_title':'none'
            }
        return render(request,'Localisation_App/faqs.html',context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Exception : Error in Faqs page. redirecting to error page ")
        

# Faqs Page Views Ends

# Faqs Serach Page Views Starts


''' 
AUTHOR : SHWETA PATIL
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON FAQS PAGE AFTER SEARCHED DATA WITH TOP AND FOOTER MENUS.

'''


def faqsSearch(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        if request.method == "POST":
            context = fetch_faqs_searched_data(request,url)
            context["topmenus"] = top_menu_items_data
            context["FooterMenuItemsdata"] = footer_menu_items_data
            logger.info("Finally, Faqs page getting displayed with serached title")
            return render(request, 'Localisation_App/faqs.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Error while, faqs search page. redirecting to error page ")
        

# Faqs Serach Page Views Ends


# Terms And Conditions Page Views Starts
''' 
AUTHOR : SHWETA PATIL, SHIVAM SHARMA
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON termsandcondition PAGE WITH TOP AND FOOTER MENUS.

'''


def termsandcondition(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        footer_data = fetch_terms_and_conditions_data()
        logger.info("Finally, Terms and Condition page getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'content': footer_data

        }
        return render(request, 'Localisation_App/footer_links/termsandconditions.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Error while,Terms and Condition page. redirecting to error page ")
        

# Terms And Conditions Page Views Ends

# Accessibility Statement Page Views Starts


''' 
AUTHOR : SHWETA PATIL, SHIVAM SHARMA
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON accessibilityStatement PAGE WITH TOP AND FOOTER MENUS.

'''


def accessibilityStatement(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        footer_data = fetch_accessibilityStatement_data()
        logger.info("Finally,accessibility_statement page getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'content': footer_data
        }
        return render(request, 'Localisation_App/footer_links/accessibility_statement.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Error while, accessibility_statement page. redirecting to error page ")
        

# Accessibility Statement Page Views Ends


# Website Policies Page Views Start

''' 
AUTHOR : SHWETA PATIL, SHIVAM SHARMA
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON websitepolicy PAGE WITH TOP AND FOOTER MENUS.

'''


def websitepolicy(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        footer_sub_data = fetch_websitepolicy_sub_data()
        content = fetch_websitepolicy_content_data()
        logger.info("Finally, websitepolicy page getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'footer_sub_data': footer_sub_data,
            "content": content
        }
        return render(request, 'Localisation_App/footer_links/websitepolicies.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Error while, websitepolicy page. redirecting to error page")
        

# Website Policies Page Views Ends


# Sitemap Page Views Starts

''' 
AUTHOR : SHWETA PATIL, SHIVAM SHARMA
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON sitemap PAGE WITH TOP AND FOOTER MENUS.

'''


def sitemap(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        footer_data = fetch_sitemap_data()
        print("data",footer_data)
        logger.info("Finally, sitemap page getting displayed")
        context = {
            'topmenus': top_menu_items_data,

Localisation_App/templates/Localisation_App/services_pages/anuvaad.html
{% extends 'Localisation_App/base.html' %} {% block title %}Anuvaad Service{% endblock %} {% load static %} {% block anuvaad %}

<link
href="{% static 'Localisation_App/css/services_pages/servicedemo.css' %}"
rel="stylesheet"
/>
<script src="https://nplt.in/demo/catalog/view/javascript/jquery/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% comment %} <script src="{% static 'Localisation_App/js/npltdemo-jquery.min.js' %}"></script>
<script src="{% static 'Localisation_App/js/jquery3-6-0.min.js' %}"></script> {% endcomment %}
<div class="container card mb-5">
    <div class="col-1 border text-center">
       <a href="{% url 'Localisation_App:services' %}" class="text-decoration-none text-black"><i class="fa fa-arrow-left p-1" aria-hidden="true"></i>Back</a>
    </div>
    <div class="card-body">
        <div class="row d-flex mb-2 justify-content-center ">
            <h2 class="text-dark text-center py-1 rounded-pill demoheading">Machine Translation</h2>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="row border px-5 py-3 rounded-4 mb-3 fs-5 demodesc">
               This Machine Translation service translates text from English to Marathi and vice versa.
            </div>
            <div class="row border p-4 rounded-4 demo">
                <div class="row">
                    <div class="col-lg-6 mb-4">
                       Select Language
                       <select id="language" class="form-select">
                         <option value="120" selected>English - Marathi</option>
                         <option value="136">Marathi - English</option>
                       </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                       <textarea class="form-control" id="source" placeholder='Input' rows="5"></textarea>
                    </div>
                    <div class="col-6">
                       <textarea class="form-control" id="output" rows="5" placeholder='Output' disabled></textarea>
                    </div>
                </div>
                <div class="row mt-2">
                  <div class="col-6 d-flex justify-content-center">
                      <button
                      class="btn btn-primary p-2"
                      type="submit"
                      >
                      Submit
                     </button>
                   </div>
                   
                </div>
                <div class="row d-flex justify-content-center">
                   <span class="loader" id="load" style="display:none"></span>
              </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(()=>{
        console.log("in ready function");
        $("button").click((e)=>{
          let text = document.getElementById('source').value;
            e.preventDefault();
            if(text != ""){
            document.getElementById('load').style.display=''
            console.log("clicked");
            console.log("text entered ", $("#source").val())
            const data={"userName":"cdac_user3@gmail.com", "password":"Welcome@123"};
            const url = "https://users-auth.anuvaad.org/anuvaad/user-mgmt/v1/users/login";
            console.log("selected language ",$("#language").val())
            $.ajax({
                url: url,
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                data: JSON.stringify(data),
            
            success: function (response) {
                console.log(response.data);
                let token = response.data.token;
                let data = {
                    model_id: $("#language").val(),
                    source_language_code: "en",
                    target_language_code: "hi",
                    sentences: [
                      {
                        src: $("#source").val(),
                        s_id: "hjf",
                      },
                    ],
                    workflowCode: "WF_S_STR",
                  };
                  let url = "https://users-auth.anuvaad.org/anuvaad-etl/wf-manager/v1/workflow/sync/initiate"; 
                  $.ajax({
                    url: url,
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json",
                    headers: { "auth-token": token },
                    data: JSON.stringify(data),
        
                    success: function (response) {
                      console.log(response);
                      document.getElementById('load').style.display='none'
                      $("#output").text(`${response.output.translations[0].tgt}\n`);
                    },
                    error: function (err) {
                      //Do Something to handle error
                       document.getElementById('load').style.display='none'
                      console.log("error in calling ", err);
                      alert("Currently service is not working...!!!");
                    },
                  });
                  
                
            },
            error: function (err) {
                //Do Something to handle error
                console.log("error in calling ", err);
                alert("Currently service is not working...!!!");
            },
           })
          }else{
            alert("enter valid text")
          }
        })
        
    })
</script>

{% endblock %}

Localisation_App/templates/Localisation_App/services_pages/gotranslate.html
{% extends 'Localisation_App/base.html' %} {% load static %} {% block title %}GoTranslate {% endblock %} {% block gotranslate_service %}
<link
  href="{% static 'Localisation_App/css/services_pages/servicedemo.css' %}"
  rel="stylesheet"
/>
<!--Content starts here-->
{% comment %} <div class="col-1 border text-center">
  <a href="{% url 'Localisation_App:services' %}" class="text-decoration-none text-black"><i class="fa fa-arrow-left p-1" aria-hidden="true"></i>Back</a>
</div> {% endcomment %}
<div class="container card mb-5">
  <div class="col-1 border text-center">
    <a href="{% url 'Localisation_App:services' %}" class="text-decoration-none text-black"><i class="fa fa-arrow-left p-1" aria-hidden="true"></i>Back</a>
  </div>
  <div class="card-body">
    <div class="row d-flex mb-2 justify-content-center">
      <h2
        class="text-dark text-center py-1 rounded-pill demoheading"
      >
        GoTranslate
      </h2>
    </div>
    <div class="row d-flex justify-content-center mb-2">
      <div
        class="row border px-5 py-3 rounded-4 mb-3 fs-5 demodesc"
      >
        GoTranslate - Website Translation & Contribution Plugin with
        Sentence-level support from C-DAC GIST, Pune, India. The main benefit of
        this plug-in is to enable end users to visit their choice of websites in
        their choosen Indian language, even if the website is not offering a
        localized version initially.
      </div>
      {% comment %}
      <div class="col d-flex"></div>
      {% endcomment %} {% comment %}
      <div class="col pb-2">
        {% endcomment %}
        <div class="row border rounded-4 text-center demo">
          <div class="col-lg-12 fs-5 p-4">
            <div>
              Integration PDF: Click
              <a
                href="https://localisation.gov.in/index.php/developer?download=60:go-translate-web-localizer-snippet"
                >here</a
              >
              to download integration pdf
            </div>
          </div>

          <div class="col-lg-12 fs-5 pt-4 pb-2 text-center">
            <div class="pb-2">Integration Video</div>
            <video width="700" height="400" controls>
              <source
                src="{% static './Localisation_App/video/Snippet_Integration_Sentence_Video.mp4' %}"
                type="video/mp4"
              />
            </video>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock%}

Localisation_App/templates/Localisation_App/services_pages/name_matcher.html
{% extends 'Localisation_App/base.html' %} {% block title %}Name Matcher
Service{% endblock %} {% load static %} {% block name_matcher %}

<link
  href="{% static 'Localisation_App/css/services_pages/servicedemo.css' %}"
  rel="stylesheet"
/>
<script src="https://gistlangserver.in/demos/nlpservices/name-match/assets/js/jquery.min.js"></script>
<div class="container name-matcher-main">
<div class=" card  mb-5">
  <div class="col-1 border text-center">
    <a
      href="{% url 'Localisation_App:services' %}"
      class="text-decoration-none text-black"
      ><i class="fa fa-arrow-left p-1" aria-hidden="true"></i>Back</a
    >
  </div>
  <div class="card-body">
    <div class="row d-flex mb-2 justify-content-center">
      <h2 class="text-dark text-center py-1 rounded-pill demoheading">
        Name Matcher
      </h2>
    </div>
    <div class="row d-flex justify-content-center">
      {% comment %} <div class="row border px-5 py-3 rounded-4 mb-3 fs-5 demodesc">
        This Name Matcher service matches covariant names
      </div> {% endcomment %}
      <div class="row border p-4 rounded-4 demo">
        <div class="col-4 pt-2">
            <input
              name="input1"
              id="name1"
              type="text"
              placeholder="Enter First Name"
              class="form-control"
              pattern="^[A-Za-z ]{3,}$"
              title="invalid name"
              required
            />
          <div id="error1" class="text-danger fw-semibold px-1 pb-2"></div>
        </div>
        <div class="col-4 pt-2">
            <input
              name="input2"
              id="name2"
              type="text"
              placeholder="Enter Second Name"
              class="form-control"
              pattern="^[A-Za-z ]{3,}$"
              title="invalid name"  
              required
            />
          <div id="error2" class="text-danger fw-semibold px-1 pb-2"></div>
        </div>
        <div class="col-4">
          <button
          type="submit"
          class="btn btn-primary btn-regular my-2"
          style="width: 100px"
          >
          Submit
        </button>
      </div>
      <div id="error_both" class="text-danger fw-semibold px31 pb-2"></div>
      </div>
    </div>
    <div id="output" class="my-2 fw-semibold fs-5"></div>
  </div>
</div>
</div>
<script>
  $(document).ready(() => {
    console.log("in ready function");
    $("button").click((e) => {
      e.preventDefault();
      $('#error1').text("")
      $('#error2').text("")
      $("#output").html('');
      $("#error_both").html('');
      let name1 = $("#name1").val();
      let name2 = $("#name2").val();

      console.log(name1)

      if(name1 == '' ){
        $('#error1').text("Please Fill First Name")
      }else if(name2 == ''){
        $('#error2').text("Please Fill Second Name")
      }else{
      const url = "https://gistlangserver2.in/AFW/NameMatch/CompareStrings";

      $.ajax({
        url: url,
        type: "GET",
        data: {
          FirstName: name1,
          SecondName: name2,
          Lenient: true,
        },
        success: function (response) {
          console.log(response);
          if(response == 10004){
            $('#error1').text("Invalid First Name")
          }
          else if(response == 10005){
            $('#error2').text("Invalid Second Name")
          }
          else if(response == 10006){
            $("#error_both").html("Invalid First & Second Names");
          }
          else{

            $("#output").html(`Maching Percentage : ${response}%\n`);
          }
        },
        error: function (err) {
          //Do Something to handle error
          console.log("error in calling ", err);
          alert("Currently service is not working...!!!");
        },
      });

    }
    });
  });
</script>
{% endblock %}

Localisation_App/templates/Localisation_App/services_pages/ttsService.html
{% extends 'Localisation_App/base.html' %}
{% load static %}
{% block title %}TTS {% endblock %}
 {% block tts_service %}
 <link
      href="{% static 'Localisation_App/css/services_pages/servicedemo.css' %}"
      rel="stylesheet"
    />
{% comment %} <div class="col-1 border text-center">
  <a href="{% url 'Localisation_App:services' %}" class="text-decoration-none text-black"><i class="fa fa-arrow-left p-1" aria-hidden="true"></i>Back</a>
</div> {% endcomment %}
<div class="container card mb-5">
  <div class="col-1 border text-center">
    <a href="{% url 'Localisation_App:services' %}" class="text-decoration-none text-black"><i class="fa fa-arrow-left p-1" aria-hidden="true"></i>Back</a>
  </div>
<form action={% url 'Localisation_App:srvTTS' %} method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% comment %} <h2 class="card-title text-dark">TTS</h2> {% endcomment %}
    <div class="card-body">
      <div class="row d-flex mb-2 justify-content-center ">
         <h2 class="text-dark text-center py-1 rounded-pill demoheading">Text To Speech</h2>
       </div>
      <div class="row d-flex justify-content-center">
         <div class="row border px-5 py-3 rounded-4 mb-3 fs-5 demodesc">
           Text-to-Speech (TTS) is a software which renders the machine readable text into Human Voice. The TTS software allows people with visual impairments or reading disabilities to listen to written works on a computer or a mobile device. Text to Speech system when integrated with screen reader would enable visually challenged users to interpret and perform computer operations with audio interface.
         </div>
         <div class="row border p-4 rounded-4 demo">
          <div class="row">
              <div class="col-lg-6 mb-4">
                 Select Language
                 {{TTS_Form.Select_Language_Pair}}
              </div>
     
              <div class="col-lg-6 mb-4">
                 Select Gender
                 {{TTS_Form.Gender}}
              </div>
          </div>
              <div class="row mb-4">
                <div class="col">
                {{TTS_Form.InputText}}
                </div>
              </div>
              {% if Status == "success" %}
                 <audio controls style="margin-top:20px; margin-left:40px;">
                    <source src={{outspeech_filepath}} type="audio/ogg">
                 </audio>
              {% endif %}<br />
                 <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> -->
               <div class="text-center">
                 <button type="submit" class="text-white px-3 py-2 rounded-2 border-none" style="width: 100px; background-color:#008ccf; border:none;">Submit</button>
               </div>
              </div>
       </div>
    </div>
  </form>
</div>
{% endblock %}