Localisation_App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views


'''
BELOW URL PATTERNS CONTAINS THE VARIOUS URLS AND THEIR RESPECTIVE CALLING VIEWS .
THE REQUEST KEYWORDS IN URL ARE MAPPED IN THIS URLPATTERN BLOCK TO DIFFERENT VIEWS WITH NAME
SITEMAP OF WEBSITE CAN BE MADE USING ALL THE URLS MENTIONED HERE IN URLPATTERN BLOCK .
'''


app_name = 'Localisation_App'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('toolsPage/', views.toolsPage, name='toolsPage'),
    path('toolsPage/<id>', views.toolsPage, name='toolsPage'),
    path('tools/', views.tools, name='tools'),
    path('toolsDownloadCounter/<int:id>',
         views.toolsDownloadCounter, name='toolsDownloadCounter'),
    path('toolsReset/', views.toolsReset, name='toolsReset'),
    path('toolsSearch/', views.toolsSearch, name='toolsSearch'),
    path('resourcesPage/', views.resourcesPage, name='resourcesPage'),
    path('resourcesPage/<id>', views.resourcesPage, name='resourcesPage'),
    path('resources/', views.resources, name='resources'),
    path('resourceDownloadCounter/<int:id>',
         views.resourceDownloadCounter, name='resourceDownloadCounter'),
    path('resourcesReset/', views.resourcesReset, name='resourcesReset'),
    path('resourceSearch/',
         views.resourceSearch, name='resourceSearch'),
    path('services/', views.services, name='services'),
    path('successstoryPage/', views.successstoryPage, name='successstoryPage'),
    path('successstory/', views.successstory, name='successstory'),
    path('successstorySearch/',
         views.successstorySearch, name='successstorySearch'),
    path('successstoryPage/<id>',views.successstoryPage, name='successstoryPage'),
    #     path('successstoryReset/', views.successstoryReset, name='successstoryReset'),
    path('submit/', views.submit, name='submit'),
    path('faqs/', views.faqs, name='faqs'),
    path('faqs/<data>',views.faqs,name='faqs'),
    path('faqsSearch/', views.faqsSearch, name='faqsSearch'),
    path('contactus/', views.contactus, name='contactus'),
    path('websitepolicy/', views.websitepolicy, name='websitepolicies'),
    path('websitepolicy/<int:id>', views.websitepolicydata,
         name='websitepolicydata'),
    path('termsandcondition/', views.termsandcondition, name='termsandcondition'),
    path('accessibilityStatement/', views.accessibilityStatement,
         name='accessibilityStatement'),
    path('sitemap/', views.sitemap, name='sitemap'),
    path('help/', views.help, name='help'),
    path('submit/<img>', views.submit, name='submit'),
    path('help/<int:id>', views.helpData, name='helpData'),
    path('srvEnableTyping/', views.srvEnableTyping, name='srvEnableTyping'),
    path('srvGoTranslateWebLocalizer/', views.srvGoTranslateWebLocalizer,
         name='srvGoTranslateWebLocalizer'),
    path('srvOnscreenKeyboard/', views.srvOnscreenKeyboard,
         name='srvOnscreenKeyboard'),
    path('srvTTS/', views.srvTTS, name='srvTTS'),
    path('srvTransliteration/', views.srvTransliteration,
         name='srvTransliteration'),


    path('goTranslate/', views.goTranslate,
         name='goTranslate'),
#     path('translation-quote/', views.translation_quote,
#          name='translation_quote'),
#     path('translation-quote-user-dashboard', views.translation_quote_user_dashboard,
#          name='translation_quote_user_dashboard'),
#     path('translation-quote-show/<str:application_number>/',
#          views.translation_quote_show, name='translation_quote_show'),
    #     path('dashboard2', views.dashboard2, name="dashboard2"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('machine-translation/', views.machine_translation,
         name="machine_translation"),
    path('name-matcher/', views.name_matcher, name="name_matcher"),
    path('empanelled_agencies/', views.empanelled_agencies,
         name="empanelled_agencies"),
    path('bhashini/', views.bhashini, name="bhashini"),
    path('anuvaad/', views.anuvaad, name="anuvaad")

]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

Localisation_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('', include('Localisation_App.urls')),
    path('search/', include('search.urls')),
]

handler404 = 'Localisation_App.views.custom_page_not_found_view'
handler500 = 'Localisation_App.views.custom_error_view'
handler403 = 'Localisation_App.views.custom_permission_denied_view'
handler400 = 'Localisation_App.views.custom_bad_request_view'

search/urls.py
from django.urls import path
from . import views


app_name= 'search'
urlpatterns = [
    path('', views.search , name='search'),

]

Localisation_App/views.py
from django.forms import ValidationError
from Localisation_Project.settings import CACHE_TTL
from .forms import TTSservice, TranslationQuoteForm
from django.contrib import messages
from django.core.mail import send_mail
from django.core.paginator import Paginator
from multiprocessing import context
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from .models import *
import random
import requests
from .word_count import crawl_data
from django.contrib.auth.models import User
import uuid
from datetime import date, datetime
from .helpers import *
import json
from bson import json_util
from django.urls import resolve
from django.contrib.auth.decorators import login_required
import logging
from datetime import date
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.core.cache import cache
from django.core import validators
logger = logging.getLogger('django')
# global str_num
# global url
CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)
import base64
import logging
import traceback
from django.conf import settings
from django.views.decorators.cache import cache_control
from dateutil import parser
from django.shortcuts import render

# Home Page View Starts

''' 
AUTHOR : SHWETA PATIL
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON HOME PAGE WITH TOP AND FOOTER MENUS.

'''


def home(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        articleData = fetch_all_article_data()
        services_name_data_list = fetch_services_heading_data()
        newsAndEventsData = fetch_all_newsAndEvents_data()
        logger.info("Finally, Home page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
            'NewsAndEventsData': newsAndEventsData,
            'Servicesdata': services_name_data_list
        }
        return render(request, 'Localisation_App/home.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Exception : Error in Home page. redirecting to error page ")
        
# Home Page View Ends

# About Us Page View Starts


''' 
AUTHOR : SHWETA PATIL
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON ABOUT US PAGE WITH TOP AND FOOTER MENUS.
THIS DYNAMIC CONTENT OF ABOUT US PAGE IS BEING RENDERED FROM 'Article' MODEL.
FOR CHANGING THE CONTENT OF ABOUT US PAGE, CHANGE THE CONTENT IN 'Article' MODEL FROM BACHEND ADMIN.
'''


def aboutus(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        logger.info("About Us URL fetched and set in 'requested_url' session")
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        articleData = fetch_aboutus_data()
        logger.info("Finally, About Us page is getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'ArticleData': articleData,
        }
        return render(request, 'Localisation_App/aboutus.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Exception : Error in About Us page. redirecting to error page ")
        # 
    

# About Us Page View Ends

# Faqs Page Views Starts


''' 
AUTHOR : SHWETA PATIL
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON FAQS PAGE WITH TOP AND FOOTER MENUS.

'''


def faqs(request, data=None):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        if data==None:
            faqs_data = fetch_faqs_data()
            logger.info("Finally, Faqs page getting displayed")
            # print("faqsdata",faqs_data)
            for d in faqs_data:
                print("q",d.FAQs_Question)
                print("a",d.FAQs_Answer)
            context = {
                'data': faqs_data,
                'FooterMenuItemsdata': footer_menu_items_data,
                'topmenus': top_menu_items_data,
                'faq_title': 'none'
            }
        
        else:
            chosen_faqs = FAQs.objects.filter(id=data)
            context={
            'data':chosen_faqs,
            'FooterMenuItemsdata':footer_menu_items_data,
            'topmenus':top_menu_items_data,
            'faq_title':'none'
            }
        return render(request,'Localisation_App/faqs.html',context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Exception : Error in Faqs page. redirecting to error page ")
        

# Faqs Page Views Ends

# Faqs Serach Page Views Starts


''' 
AUTHOR : SHWETA PATIL
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON FAQS PAGE AFTER SEARCHED DATA WITH TOP AND FOOTER MENUS.

'''


def faqsSearch(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        if request.method == "POST":
            context = fetch_faqs_searched_data(request,url)
            context["topmenus"] = top_menu_items_data
            context["FooterMenuItemsdata"] = footer_menu_items_data
            logger.info("Finally, Faqs page getting displayed with serached title")
            return render(request, 'Localisation_App/faqs.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Error while, faqs search page. redirecting to error page ")
        

# Faqs Serach Page Views Ends


# Terms And Conditions Page Views Starts
''' 
AUTHOR : SHWETA PATIL, SHIVAM SHARMA
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON termsandcondition PAGE WITH TOP AND FOOTER MENUS.

'''


def termsandcondition(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        footer_data = fetch_terms_and_conditions_data()
        logger.info("Finally, Terms and Condition page getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'content': footer_data

        }
        return render(request, 'Localisation_App/footer_links/termsandconditions.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Error while,Terms and Condition page. redirecting to error page ")
        

# Terms And Conditions Page Views Ends

# Accessibility Statement Page Views Starts


''' 
AUTHOR : SHWETA PATIL, SHIVAM SHARMA
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON accessibilityStatement PAGE WITH TOP AND FOOTER MENUS.

'''


def accessibilityStatement(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        footer_data = fetch_accessibilityStatement_data()
        logger.info("Finally,accessibility_statement page getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'content': footer_data
        }
        return render(request, 'Localisation_App/footer_links/accessibility_statement.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Error while, accessibility_statement page. redirecting to error page ")
        

# Accessibility Statement Page Views Ends


# Website Policies Page Views Start

''' 
AUTHOR : SHWETA PATIL, SHIVAM SHARMA
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON websitepolicy PAGE WITH TOP AND FOOTER MENUS.

'''


def websitepolicy(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        footer_sub_data = fetch_websitepolicy_sub_data()
        content = fetch_websitepolicy_content_data()
        logger.info("Finally, websitepolicy page getting displayed")
        context = {
            'topmenus': top_menu_items_data,
            'FooterMenuItemsdata': footer_menu_items_data,
            'footer_sub_data': footer_sub_data,
            "content": content
        }
        return render(request, 'Localisation_App/footer_links/websitepolicies.html', context)
    except Exception as e:
        logger.error('%s' % type(e))
        logger.error(
            "Error while, websitepolicy page. redirecting to error page")
        

# Website Policies Page Views Ends


# Sitemap Page Views Starts

''' 
AUTHOR : SHWETA PATIL, SHIVAM SHARMA
DATE : 24-07-2022
BELOW FUNCTION IS RENDERING CONTENT ON sitemap PAGE WITH TOP AND FOOTER MENUS.

'''


def sitemap(request):
    try:
        url = resolve(request.path_info).url_name
        request.session['requested_url'] = url
        top_menu_items_data = fetch_top_menu_items()
        footer_menu_items_data = fetch_footer_menu_items()
        footer_data = fetch_sitemap_data()
        print("data",footer_data)
        logger.info("Finally, sitemap page getting displayed")
        context = {
            'topmenus': top_menu_items_data,

Localisation_App/templates/Localisation_App/footer.html
{% load static %}

<link
      href="{% static 'Localisation_App/css/footer-links.css' %}"
      rel="stylesheet"
    />
    
<div class="sticky-button">
  <img src="{% static './Localisation_App/img/gotranslate.jpg' %}" alt="..." class="sticky-img" /><span><a target="_blank" href="https://chrome.google.com/webstore/detail/gotranslate-web-localizer/lcmdfppjojeebpjblgmookbnfmbnjhhh?hl=en">GoTranslate Plugin</a> </span>
  
 </div>
 <div class="sticky-button-2">
  <img src="{% static './Localisation_App/img/gem.jpg' %}" alt="..." class="sticky-img"/><span><a target="_blank" href="https://gem.gov.in/">GEM Portal</a> </span>
  
 </div>
 <div class="sticky-button-3">
  <img src="{% static './Localisation_App/img/Shake.png' %}" alt="..." class="sticky-img" /><span><a target="_blank" href="https://chrome.google.com/webstore/detail/gotranslate-web-localizer/lcmdfppjojeebpjblgmookbnfmbnjhhh?hl=en">Empanelled Agencies</a> </span>
  
 </div>
 <div class="sticky-button-4">
  <img src="{% static './Localisation_App/img/nplt3.jpg' %}" alt="..." class="sticky-img" /><span><a target="_blank" href="https://chrome.google.com/webstore/detail/gotranslate-web-localizer/lcmdfppjojeebpjblgmookbnfmbnjhhh?hl=en">NPLT</a> </span>
  
 </div>
 <div class="row footer-link-section">
   <div class="col-1">

   </div>
  <div class="col-2 footer-section-cards">
    <img src="{% static './Localisation_App/img/community1.png' %}" alt="..." style="color:white" class="footer-link-img" />
   <a target="_blank" href="https://www.tdil-dc.in/index.php?option=com_communityprofile&Itemid=548&lang=en">TDIL Community</a> 
  </div>
  <div class="col-2 footer-section-cards">
    <img src="{% static './Localisation_App/img/sitemaps1.png' %}" alt="..." class="footer-link-img" />
    <a target="_blank" href="{% url 'Localisation_App:sitemap' %}">Sitemaps</a> 
  </div>
  <div class="col-2 footer-section-cards">
    <img src="{% static './Localisation_App/img/call1.png' %}" alt="..." class="footer-link-img" />
    <a target="_blank" href="{% url 'Localisation_App:contactus' %}">
      Contact Us
    </a>
  </div>
  <div class="col-2 footer-section-cards">
    <img src="{% static './Localisation_App/img/dashboard1.png' %}" alt="..." class="footer-link-img" />
    <a target="_blank" href="{% url 'Localisation_App:dashboard' %}">  Dashboard</a>
  
  </div>
  <div class="col-2 footer-section-cards">
    <img src="{% static './Localisation_App/img/training1.png' %}" alt="..." class="footer-link-img" />
    <a target="_blank"  href="{% url 'Localisation_App:contactus' %}" >     Training</a>

  </div>
  

</div>
 
 <div class="footer">
 
   <div class="row">
     <div class="col-sm-12 col-lg-3  footer-left">
       <h3 class="quick">Quick Links</h3>

       <p>
       <ul style="list-style: none;">
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:home' %}">{{ topmenus.0 }}</a></li>
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:websitepolicies' %}">{{ FooterMenuItemsdata.0 }}</a>
         </li>
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:termsandcondition' %}">{{ FooterMenuItemsdata.1 }}</a>
         </li>
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:accessibilityStatement' %}">{{ FooterMenuItemsdata.2 }}</li>
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:sitemap' %}">{{ FooterMenuItemsdata.3 }}</a></li>
         <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
             href="{% url 'Localisation_App:help' %}">{{ FooterMenuItemsdata.4 }}</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
          href="{% url 'Localisation_App:empanelled_agencies' %}">{{ FooterMenuItemsdata.5 }}</a></li>
          <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a
            href="{% url 'Localisation_App:faqs' %}">{{ FooterMenuItemsdata.6 }}</a></li>
       </ul>
       </p>
     </div>
     <div class="col-sm-12 col-md-12 col-lg-6  footer-center">
      <a href="https://www.meity.gov.in/" target="_blank"><img src="{% static './Localisation_App/img/meity.png' %}" class="footer-image-center" alt="..." /></a>
       <hr class="line">
       <div class="row ">

         <div class="col-sm-3 col-md-3 col-lg-3 footer-logo-1 text-center px-2"> <a href="https://digitalindia.gov.in/" target="_blank"><img
             src="{% static './Localisation_App/img/digital-india.png' %}" class="img-fluid" alt="..." /></a></div>
         <div class="col-sm-12 col-md-3 col-lg-3 footer-logo-4 text-center px-5"> <a href="https://www.mygov.in/" target="_blank"><img
             src="{% static './Localisation_App/img/mygov.png' %}" height="60px" width="120px" alt="..." /></a></div>
         <div class="col-sm-12 col-md-3 col-lg-3 footer-logo-2 text-center pt-1 px-1"> <a href="https://www.tdil-dc.in/index.php?lang=en" target="_blank"><img
             src="{% static './Localisation_App/img/tdil.png' %}" class="img-1" alt="..." /></a></div>
         {% comment %} <div class="col-sm-12 col-md-3 col-lg-3 footer-logo-3"> <img
             src="{% static './Localisation_App/img/bhashini-logo.png' %}" height="80px" width="120px" class="" alt="..." /></div> {% endcomment %}
             <div class="col-sm-3 col-md-3 col-lg-3 footer-logo-1 text-center"> <a href="https://meitystartuphub.in/" target="_blank"><img
              src="{% static './Localisation_App/img/Meity_startup_hub.png' %}" class="img-fluid" alt="..." /></a></div>
             
       </div>
     </div>

     <div class="col-lg-6 footer-right">
      <h3 class="quick">IDN Links</h3>
 
      <p>
      <ul style="list-style: none;">
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://www.cdac.in/">सीडैक.भारत</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://www.meity.gov.in/">एमईआईटीवाई.सरकार.भारत</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://www.india.gov.in/">इंडिया.सरकार.भारत</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://innovate.mygov.in/">इनोवेटइंडिया.मेरीसरकार.भारत</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://registry.in/">रजिस्ट्री.भारत</a></li>
        <li><span> <img src="{% static './Localisation_App/img/bullet.png' %}" alt="..." /></span><a target="_blank" href="https://nixi.in/">निक्सी.भारत</a></li>

      </ul>
      </p>
       <!-- <h5 class="designed">
         Designed, Developed & Hosted by
       </h5>
       <h6>CDAC GIST Pune</h6> -->
       <br>
       <!-- <img src="{% static './Localisation_App/img/Group12.jpg' %}" class="footer-gist-section" alt="..." /> -->
     </div>
   </div>
   <div class="copyright-section">
    <h5 class="designed">
      Designed, Developed & Hosted by <span style="font-weight: 700;"><a target="_blank" href="https://www.cdac.in/" style="text-decoration: none;color:white;"> CDAC GIST</a></span> Pune
    </h5>
 
     Copyright © 2022 LPMF. All Rights Reserved.
   </div>
 </div>

Localisation_App/templates/Localisation_App/serverdown.html
<html>
  <head></head>

  <body>
    <h4>Server is down</h4>
  </body>

  <html></html>
</html>

Localisation_App/templates/Localisation_App/topmenu.html
{% load static %}

<nav
  class="navbar navbar-expand-lg bg-light sticky-top"
  style="
    background-color: #ffffff !important;
    box-shadow: 0px 0.5px 13px 1px rgb(230, 228, 228);
  "
>
  <div class="container-fluid">
    <a class="navbar-brand mx-5" href="{% url 'Localisation_App:home' %}">
      <img
        src="{% static './Localisation_App/img/llogo.png' %}"
        class="d-block w-100"
        alt="..."
    /></a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item {% if request.path == '/' %}active{% endif %}">
          <a
            class="items"
            aria-current="page"
            href="{% url 'Localisation_App:home' %}"
            >{{ topmenus.0 }}</a
          >
        </li>
        <li
          class="nav-item {% if request.path == '/aboutus/' %}active{% endif %}"
        >
          <a class="items" href="{% url 'Localisation_App:aboutus' %}"
            >{{ topmenus.1 }}</a
          >
        </li>

        <li
          class="nav-item dropdown {% if request.path == '/services/' or request.path == '/toolsPage/' or request.path == '/resourcesPage/' %}active{% endif %}"
        >
          <a
            class="nav-link dropdown-toggle items"
            style="padding: 0px"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Our Products
          </a>
          <ul
            class="dropdown-menu"
            style="padding-left: 12px"
            aria-labelledby="navbarDropdownMenuLink"
          >
            <li class="nav-item active">
              <a class="items" href="{% url 'Localisation_App:services' %}"
                >{{ topmenus.2 }}</a
              >
            </li>
            <li
              class="nav-item {% if request.path == '/toolsPage/' %}active{% endif %}"
            >
              <a class="items" href="{% url 'Localisation_App:toolsPage' %}"
                >{{ topmenus.3 }}</a
              >
            </li>
            <li
              class="nav-item {% if request.path == '/resourcesPage/' %}active{% endif %}"
            >
              <a class="items" href="{% url 'Localisation_App:resourcesPage' %}"
                >{{ topmenus.10 }}</a
              >
            </li>
          </ul>
        </li>

        <li
          class="nav-item {% if request.path == '/successstoryPage/' %}active{% endif %}"
        >
          <a class="items" href="{% url 'Localisation_App:successstoryPage' %}"
            >{{ topmenus.4 }}</a
          >
        </li>
        <li
          class="nav-item {% if request.path == '/dashboard/' %}active{% endif %}"
        >
          <a class="items" href="{% url 'Localisation_App:dashboard' %}"
            >{{ topmenus.12 }}</a
          >
        </li>
        <li class="nav-item {% if request.path == '/faqs/' %}active{% endif %}">
          <a class="items" href="{% url 'Localisation_App:faqs' %}"
            >{{ topmenus.5 }}</a
          >
        </li>
        <li
          class="nav-item {% if request.path == '/contactus/' %}active{% endif %}"
        >
          <a class="items" href="{% url 'Localisation_App:contactus' %}"
            >{{ topmenus.6 }}</a
          >
        </li>
       
        </li>
      </ul>

      {% comment %} <div class="nav-item animate__animated animate__pulse animate__infinite">
        <div class="quote">
          <a
            class="item-button"
            href="{% url 'Localisation_App:translation_quote' %}"
            >{{ topmenus.9 }}</a
          >
        </div>
      </div> {% endcomment %}
    </div>
  </div>
</nav>